name: "Template Directory Tests"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./template-directory
      with:
        directory: ./template-directory/test
    - run: cat ./template-directory/test/template.yml
